/// <reference types="node" />
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma's schema engine uses its own SSL parser. Keep the provider URL
    // intact here; runtime node-postgres normalization lives in src/lib/prisma.
    url: process.env["DATABASE_URL"],
  },
});
